import type { Metadata } from 'next';

import * as s from './page.css';

import { lightTheme } from '@kimdw524/dds';

import Link from 'next/link';
import Navbar from '@/components/layout/Navbar';

export const metadata: Metadata = {
  title: 'Next blog',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lightTheme}>
        <Navbar />
        <nav className={s.nav}>
          <Link href="/">Home</Link>
          <Link href="/posts">Posts</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
